### ISSUE TITLE
Action Failing

### ISSUE THREAD

**Issue by jacobblyons** [kuler90/activate-unity#3]
Hello. 

This action has worked great for me in the past, but it recently stopped working. 

my workflow:
```
- name: Setup Unity
  uses: kuler90/setup-unity@v1.0.6
  with:
    unity-version: 2020.2.2f1
    unity-modules: 
      mac-il2cpp
      windows-il2cpp
      ios
      android
      
- name: Activate Unity
  uses: kuler90/activate-unity@v1
  with:
    unity-username: ${{ secrets.UNITY_USERNAME }}
    unity-password: ${{ secrets.UNITY_PASSWORD }}
```
the error:

```
/Applications/Unity/Hub/Editor/2020.2.2f1/Unity.app/Contents/MacOS/Unity -batchmode -nographics -quit -logFile - -createManualActivationFile
[Licensing::Module] Channel doesn't exist: "LicenseClient-runner"
Launching external process: /Applications/Unity/Hub/Editor/2020.2.2f1/Unity.app/Contents/Frameworks/UnityLicensingClient.app/Contents/Resources/Unity.Licensing.Client
[Licensing::Module] Successfully launched the LicensingClient (PId: 1771)
[Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-runner" (connect: 0.70s, validation: 0.07s, handshake: 0.30s)
[Licensing::Module] Connected to LicensingClient (PId: 1771, launch time: 0.00, total connection time: 1.07s)
Entitlement-based licensing initiated
[LicensingClient] Licenses updated successfully

 Generating manual activation license file.

LICENSE SYSTEM [202156 5:26:40] License activate file written to: Unity_v2020.2.2f1.alf

 Manual activation license file saved.
Error: Navigation timeout of 30000 ms exceeded
```

Any help would be greatly appreciated.

Thanks!
